title: "BeeGFS Deployment"
schemaVersion: 1.0.0
version: "20200303"
locale: "en"

groupings:
  - title: "Hidden General Configuration"
    visible: false
    variables:
    - tenancy_ocid
    - compartment_ocid
    - region
    - scripts_directory
    - ssh_user
    - volume_attach_device_mapping
    - volume_type_vpus_per_gb_mapping
    - ad_number
    - images
    - mp_listing_id
    - mp_listing_resource_id
    - mp_listing_resource_version
    - use_marketplace_image
    - ha_vip_mapping
    - hpc_cn_mp_listing_id
    - hpc_cn_mp_listing_resource_id
    - hpc_cn_mp_listing_resource_version
  - title: "VCN Configuration"
    visible: true
    variables:
    - use_existing_vcn
    - vpc_cidr
    - vcn_id
    - bastion_subnet_id
    - storage_subnet_id
    - fs_subnet_id
  - title: "General Deployment Configuration"
    visible: true
    variables:
    - ssh_public_key
    - ad_name
    - use_custom_name
    - cluster_name
    - beegfs_high_availability
    - management_high_availability
    - management_vip_private_ip
    - metadata_high_availability
    - metadata_use_shared_disk
    - metadata_vip_private_ip
    - storage_high_availability
    - storage_use_shared_disk
    - storage_vip_private_ip
  - title: "Bastion Instance Configuration"
    visible: true
    variables:
    - bastion_shape
    - bastion_node_count
    - bastion_hostname_prefix
  - title: "BeeGFS Management Service Configuration"
    visible: true
    variables:
    - management_server_shape
    - management_server_node_count
    - management_server_hostname_prefix
    - management_server_disk_count
    - management_server_disk_size
    - management_server_disk_vpus_per_gb
  - title: "BeeGFS Metadata Service Configuration"
    visible: true
    variables:
    - metadata_server_shape
    - metadata_server_node_count
    - metadata_server_hostname_prefix
    - metadata_server_disk_count
    - metadata_server_disk_size
    - metadata_server_disk_vpus_per_gb
  - title: "BeeGFS Storage Service Configuration"
    visible: true
    variables:
    - storage_server_shape
    - storage_server_node_count
    - storage_server_hostname_prefix
  - title: "BeeGFS Storage Tiering Configuration"
    visible: true
    variables:
    - storage_tier_1_disk_type
    - storage_tier_1_disk_count
    - storage_tier_1_disk_size
    - storage_tier_2_disk_type
    - storage_tier_2_disk_count
    - storage_tier_2_disk_size
    - storage_tier_3_disk_type
    - storage_tier_3_disk_count
    - storage_tier_3_disk_size
    - storage_tier_4_disk_type
    - storage_tier_4_disk_count
    - storage_tier_4_disk_size
  - title: "BeeGFS Client Instance Configuration"
    visible: true
    variables:
    - client_node_shape
    - client_node_count
    - client_node_hostname_prefix
  - title: "BeeGFS Filesystem Configuration"
    visible: true
    variables:
    - beegfs_stripe_size
    - beegfs_mount_point


# Add variable here ,  if you want to do input validation or else it does not need to be included here.
variables:
  ssh_public_key:
    title: "SSH Public Key"
    description: "Public key for all compute instances."
    type: string
    required: true

  ad_name:
    title: "Availability Domain"
    description: "Availability Domain where filesystem is deployed."
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true

  bastion_shape:
    title: "Bastion Compute Shape"
    description: "Shape for bastion instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.2"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  bastion_node_count:
    title: "Number of bastion"
    description: "Number of bastion instances."
    type: integer
    default: 1
    minimum: 1
    maximum: 1
    required: true

  bastion_hostname_prefix:
    type: string
    required: true
    default: "bastion-"
    description: "Bastion hostname prefix "

  management_server_shape:
    title: "Management Server Compute Shape"
    description: "Shape for management server instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.2"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  management_server_node_count:
    title: "Number of management server"
    description: "Number of management server instances. Minimum one instance required for non high availability setup and two for highly available management service."
    type: integer
    default: 1
    minimum: 1
    maximum: 2
    required: true

  management_server_hostname_prefix:
    type: string
    required: true
    default: "mgs-server-"
    description: "Management server hostname prefix "

  management_server_disk_count:
    title: "Number of block volumes"
    description: "Number of block volumes for each management server. Local NVME will be prefered (and block unused) if available. Maximum 1 local NVMe SSD or 1 Block Volume allowed. Min: 0. "
    type: integer
    default: 1
    minimum: 0
    maximum: 1
    required: true

  management_server_disk_size:
    title: "Block volume size"
    description: "Size in GB for block volumes attached to management server, min 50GB is more than enough."
    type: integer
    default: 50
    minimum: 50
    maximum: 32768
    required: true

  management_server_disk_vpus_per_gb:
    description: "Block volume performance"
    type: enum
    enum:
    - "Local_NVMe_SSD"
    - "High"
    - "Balanced"
    - "Low"
    required: true
    default: "Balanced"

  metadata_server_shape:
    title: "Metadata Server Compute Shape"
    description: "Shape for metadata server instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.8"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  metadata_server_node_count:
    title: "Number of metadata server"
    description: "Number of metadata server instances."
    type: integer
    minimum: 1
    default: 1
    required: true

  metadata_server_hostname_prefix:
    type: string
    required: true
    default: "metadata-server-"
    description: "Metadata server hostname prefix "

  metadata_server_disk_count:
    title: "Number of block volumes"
    description: "Number of block volumes for each metadata server. if >1 disks will form a RAID0 array. Local NVME will be prefered (and block unused) if available."
    type: integer
    default: 1
    minimum: 0
    maximum: 1
    required: true

  metadata_server_disk_size:
    title: "Block volume size"
    description: "Size in GB for block volumes attached to metadata server, min 50. Example - 500GB High Performance Block Volume will give you 35K IOPS and should be enough to store 150 million files."
    type: integer
    default: 500
    minimum: 50
    maximum: 32768
    required: true

  metadata_server_disk_vpus_per_gb:
    description: "Block volume performance"
    type: enum
    enum:
    - "High"
    - "Balanced"
    - "Low"
    required: true
    default: "High"

  storage_server_shape:
    title: "Storage Server Compute Shape"
    description: "Shape for storage server instances."
    type: oci:core:instanceshape:name
    default: "BM.Standard2.52"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  storage_server_node_count:
    title: "Number of storage server"
    description: "Number of storage server instances."
    type: integer
    default: 2
    minimum: 1
    required: true

  storage_server_hostname_prefix:
    type: string
    required: true
    default: "storage-server-"
    description: "Storage server hostname prefix "

  storage_tier_1_disk_type:
    title: "Storage tier-1 disk type"
    description: "Use Local_NVMe_SSD value only if DenseIO shape was selected for Storage server. Otherwise select block volume storage types (high, balanced, low) based on your performance needs. Valid values are Local_NVMe_SSD, High, Balanced, Low."
    type: enum
    enum:
    - "Local_NVMe_SSD"
    - "High"
    - "Balanced"
    - "Low"
    required: true
    default: "High"


  storage_tier_1_disk_count:
    title: "Number of block volumes"
    description: "Number of local NVMe SSD/block volume disk. Each attached as JBOD (no RAID)."
    type: integer
    default: 8
    minimum: 1
    maximum: 31
    required: true

  storage_tier_1_disk_size:
    title: "Block volume size"
    description: "If Storage Tier-1 Disk Type is Local_NVMe_SSD, then this field will be ignored.  Otherwise set Size in GB for each block volume/disk, min 50."
    type: integer
    default: 800
    minimum: 50
    maximum: 32768
    required: true

  storage_tier_2_disk_type:
    title: "Storage tier-2 disk type"
    description: "Select block volume storage types (high, balanced, low) based on your performance needs. Valid values are None, High, Balanced or Low."
    default: None
    type: enum
    enum:
    - "None"
    - "High"
    - "Balanced"
    - "Low"
    required: false

  storage_tier_2_disk_count:
    title: "Number of block volumes"
    description: "Number of block volume disk per instance. Each attached as JBOD (no RAID)."
    type: integer
    default: 0
    minimum: 0
    maximum: 31
    required: false

  storage_tier_2_disk_size:
    title: "Block volume size"
    description: "Size in GB for each block volume/disk, min 50."
    type: integer
    default: 50
    minimum: 50
    maximum: 32768
    required: false

  storage_tier_3_disk_type:
    title: "Storage tier-3 disk type"
    description: "Select None or block volume storage types (high, balanced, low) based on your performance needs. Valid values are None, Balanced or Low."
    default: None
    type: enum
    enum:
    - "None"
    - "Balanced"
    - "Low"
    required: false

  storage_tier_3_disk_count:
    title: "Number of block volumes"
    description: "Number of block volume disk per instance. Each attached as JBOD (no RAID)."
    type: integer
    default: 0
    minimum: 0
    maximum: 31
    required: false

  storage_tier_3_disk_size:
    title: "Block volume size"
    description: "Size in GB for each block volume/disk, min 50."
    type: integer
    default: 50
    minimum: 50
    maximum: 32768
    required: false

  storage_tier_4_disk_type:
    title: "Storage tier-4 disk type"
    description: "Select None or block volume storage types (high, balanced, low) based on your performance needs. Valid values are None or Low."
    default: None
    type: enum
    enum:
    - "None"
    - "Low"
    required: false

  storage_tier_4_disk_count:
    title: "Number of block volumes"
    description: "Number of block volume disk per instance. Each attached as JBOD (no RAID)."
    type: integer
    default: 0
    minimum: 0
    maximum: 31
    required: false

  storage_tier_4_disk_size:
    title: "Block volume size"
    description: "Size in GB for each block volume/disk, min 50."
    type: integer
    default: 50
    minimum: 50
    maximum: 32768
    required: false

  client_node_shape:
    title: "Client Compute Shape"
    description: "Shape for client instances."
    type: oci:core:instanceshape:name
    default: "VM.Standard2.24"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  client_node_count:
    title: "Number of clients"
    description: "Number of client instances."
    type: integer
    default: 1
    minimum: 0
    required: true

  client_node_hostname_prefix:
    type: string
    required: true
    default: "client-"
    description: "Client hostname prefix "

  beegfs_stripe_size:
    type: string
    required: true
    default: "1m"
    description: "Default file stripe size (aka chunk_size) used by clients to striping file data and send to desired number of storage targets (OSTs). Example: 1m, 512k, 2m, etc"

  beegfs_mount_point:
    type: string
    required: true
    default: "/mnt/beegfs"
    description: "Mount point on client instances for BeeGFS filesystem. "

  beegfs_high_availability:
    type: boolean
    required: true
    default: false
    description: "Select checkbox to deploy BeeGFS file system with high availability."
    visible: true

  management_high_availability:
    type: boolean
    required: false
    default: false
    description: "Select checkbox to deploy BeeGFS Management service with high availability(HA). Two nodes configured with Network Attached Shared Disk/Block Volume Storage and Corosync/Pacemaker for HA"
    visible: ${beegfs_high_availability}

  metadata_high_availability:
    type: boolean
    required: false
    default: false
    description: "Select checkbox to deploy BeeGFS Metadata service with high availability(HA)."
    visible: ${beegfs_high_availability}

  storage_high_availability:
    type: boolean
    required: false
    default: false
    description: "Select checkbox to deploy BeeGFS Storage service with high availability(HA)."
    visible: ${beegfs_high_availability}

  metadata_use_shared_disk:
    type: boolean
    required: false
    default: false
    description: "Select checkbox to use Network Attached Shared Disks for high availability(HA) to reduce storage cost.  If checkbox is not selected, it will use BeeGFS Buddy Mirror/Replication for HA."
    visible:
      and:
        - ${beegfs_high_availability}
        - ${metadata_high_availability}

  storage_use_shared_disk:
    type: boolean
    required: false
    default: false
    description: "Select checkbox to use Network Attached Shared Disks for high availability(HA) to reduce storage cost.  If checkbox is not selected, it will use BeeGFS Buddy Mirror/Replication for HA."
    visible:
      and:
        - ${beegfs_high_availability}
        - ${storage_high_availability}

  ad_number:
    description: "Shadowed TF value to ignore"
    type: integer
    required: true
    default: -1

  scripts_directory:
    type: string
    required: true
    default: "script"
    description: "Folder which has all the scripts."

  ssh_user:
    type: string
    required: true
    default: "opc"
    description: "opc for OracleLinux & CentOS, ubuntu for Ubuntu OS."

  mp_listing_id:
    type: string
    required: true
    description: "Marketplace Listing ID"

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: "Marketplace Image OCID"
    dependsOn:
      compartmentId: ${compartment_ocid}

  mp_listing_resource_version:
    type: string
    required: true
    description: "Marketplace Listing package version"

  use_existing_vcn:
    type: boolean
    title: "Use Existing VCN"
    description: "Select checkbox, to use existing VCN, otherwise new VCN, subnets and related network resources will be created"
    required: true
    default: false

  vpc_cidr:
    title: "VPC CIDR"
    description: "Network CIDR to use for VPC/VCN."
    type: string
    default: "10.0.0.0/16"
    required: true
    visible:
      not:
        - ${use_existing_vcn}

  vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN OCID"
    description: "Existing VCN OCID"
    dependsOn:
      compartmentId: ${compartment_ocid}
    visible: ${use_existing_vcn}
    required: true

  bastion_subnet_id:
    type: oci:core:subnet:id
    title: "Bastion Subnet OCID"
    description: "Public Subnet OCID to deploy a Bastion node to access the file system nodes in private subnets.  Ensure the Subnet is regional subnet or is in the same Availability Domain selected in this deployment template"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_id}
      hidePrivateSubnet: true
    visible: ${use_existing_vcn}
    required: true

  storage_subnet_id:
    type: oci:core:subnet:id
    title: "Storage Subnet OCID"
    description: "Private Subnet OCID for file servers to use for their primary NIC (NIC0) and Primary VNIC. File servers use this subnet to read/write data to Storage. Ensure the Subnet is regional subnet or is in the same Availability Domain selected in this deployment template"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_id}
      hidePublicSubnet: true
    visible: ${use_existing_vcn}
    required: true

  fs_subnet_id:
    type: oci:core:subnet:id
    title: "Filesystem Subnet OCID"
    description: "Private Subnet for file servers and client nodes to send and receive data to each other.  This subnet is not used to send/receive data to Storage system. Ensure the Subnet is regional subnet or is in the same Availability Domain selected in this deployment template"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_id}
      hidePublicSubnet: true
    visible: ${use_existing_vcn}
    required: true

  management_vip_private_ip:
    type: string
    title: "Management Virtual IP for HA (Highly Availability)"
    description: "Floating Virtual IP to assign to an active node in an active/passive HA cluster. Only one VIP is needed.  Provide an unused private IP from FS private subnet. Refer to network architecture diagrams here: https://github.com/oracle-quickstart/oci-beegfs."
    required: false
    default: "10.0.2.254"
    visible:
      and:
        - ${beegfs_high_availability}
        - ${management_high_availability}

  metadata_vip_private_ip:
    type: string
    title: "Metadata Virtual IPs for HA (Highly Availability)"
    description: "Floating Virtual IPs to assign to each active node in an active/passive HA pair. For every two Metadata servers, one VIP is needed.  If you have four Metadata servers, then two VIPs need to be provided as a comma seperated list.  Provide an unused private IP from FS private subnet. Refer to network architecture diagrams here: https://github.com/oracle-quickstart/oci-beegfs."
    required: false
    default: "10.0.2.253,10.0.2.252"
    visible:
      and:
        - ${beegfs_high_availability}
        - ${metadata_high_availability}
        - ${metadata_use_shared_disk}

  storage_vip_private_ip:
    type: string
    title: "Storage Virtual IPs for HA (Highly Availability)"
    description: "Floating Virtual IPs to assign to each active node in an active/passive HA pair. For every two Storage servers, one VIP is needed.  If you have four Storage servers, then two VIPs need to be provided as a comma seperated list.  Provide an unused private IP from FS private subnet. Refer to network architecture diagrams here: https://github.com/oracle-quickstart/oci-beegfs."
    required: false
    default: "10.0.2.251,10.0.2.250"
    visible:
      and:
        - ${beegfs_high_availability}
        - ${storage_high_availability}
        - ${storage_use_shared_disk}
  use_custom_name: 
    type: boolean
    title: "use custom cluster name"
    description: "Use custom name for the cluster" 
    required: true
    default: false
  cluster_name: 
    title: "Name of the cluster" 
    description: "Custom cluster name"
    type: string
    visible: 
      and: 
        - ${use_custom_name}
  ha_vip_mapping:
    type: string
    title: "ha_vip_mapping"
    description: "Variable Map to use default VIP for HA failover."
    default: ""
  hpc_cn_mp_listing_id:
    type: string
    title: "hpc_cn_mp_listing_id"
    description: "hpc_cn_mp_listing_id."
    default: ""
  hpc_cn_mp_listing_resource_id:
    type: string
    title: "hpc_cn_mp_listing_resource_id"
    description: "hpc_cn_mp_listing_resource_id."
    default: ""
  hpc_cn_mp_listing_resource_version:
    type: string
    title: "hpc_cn_mp_listing_resource_version"
    description: "hpc_cn_mp_listing_resource_version."
    default: ""

